# Generated by Django 5.0.7 on 2024-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAppImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('imgURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAppText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalApp',
        ),
    ]
